#!/bin/sh
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

PAGE=1
SEARCH=""
DELIM="\t"
NOPROMPT=""
NOCLIPBOARD=""
COMMAND=""
CSV=0
CSV_HEADER=1
LINK_CONV=0

C_LE="31"
C_SE="32"
C_PAGES="32"
C_SIZE="33"
C_CATEGORY="34"
C_EXTENSION="34"
C_VOLUME="34"
C_LANGUAGE="34"
C_DOWNLOADED="35"
C_HEALTH="35"
C_AUTHOR="35"
C_DATE="36"
C_NAME="39"
COLOR=1

alias ucurl='curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36" -H "Accept-Encoding: gzip, deflate" --compressed'

arg0="$(basename "$0")"

print_help() {
    printf "%s [SOURCE] [OPTION]... [PATTERN]\nSearch torrent sites for PATTERN in SOURCE.\nExample: %s tpb -s size -p 2 'archlinux'\n\n" "$arg0" "$arg0"
    printf "Sources:\n  tpb|thepiratebay\n  lt|limetorrents\n  1337x\n  rarbg\n  nyaa\n  libgen\n\n"
    printf "Universal options:\n"
    printf "  -d,  --domain DOMAIN\t\tset domain to DOMAIN\n"
    printf "  -D,  --delimiter DELIM\tset delimiter to DELIM, by default '\\\\t'\n"
    printf "  -p,  --page NUM\t\tshow page at NUM\n"
    printf "  -C,  --no-color\t\tdisable coloring of output\n"
    printf "       --no-prompt\t\tdo not show prompt\n"
    printf "       --no-clipboard\t\tdo not copy results to clipboard, just print them to stderr\n"
    printf "       --choose COMMAND\t\tuse COMMAND to choose\n"
    printf "       --csv\t\t\tprint lines simply delimited by DELIM, by default the first line will be a csv header\n"
    printf "       --no-csv-header\t\t\tdo not print csv header\n"
    printf "       --link-conv\t\tconvert links to their real destination (works only with --csv and --json options)\n"
    printf "  -h,  --help\t\t\tshow help\n\n"
    printf "Further help can be found by typing %s SOURCE -h.\n" "$arg0"
    printf "Selection is done by inputting numbers of lines delimited by spaces or commas\n" "$arg0"
    printf "Output will be copied via xclip.\n"
}

pastelines() {
    awk -v "fields=$1" -v "raw_colors=$2" 'function print_fields(lines,fields,step,colors) {
            ORS = ""
            for (i = 0; i < step; i++) {
                for (j = 0; j < fields; j++) {
                    if (j != 0)
                        print "'"$DELIM"'"
                    if ('"$COLOR"')
                        print "\033["colors[j+1]"m"lines[(step*j)+i]"\033[0m"
                    else
                        print lines[(step*j)+i]
                }
                printf "\n"
            }
        }

        BEGIN {
            l=0;
            split(raw_colors,colors,",");
        }

        { lines[l++]=$0 }

        END {
            if (l >= fields)
            if (l%fields == 0) {
                    step = l/fields
                    print_fields(lines,fields,step,colors)
            } else
                print "length of some data fields does not match the others"
        }'
}

tpb_help() {
    printf '  -s,  --sort TYPE\t\tsort using TYPE that can be: name, size, date, se, le, author, category\n'
    printf "  -r,  --reverse\t\tsort in reverse\n"
}

tpb_searchtrans() {
    tr ' ' '.'
}

tpb_settings() {
    [ -z "$DOMAIN" ] && DOMAIN="https://tpb.party"
    SORT='7'
    case "$sort_type" in
        name) SORT='1';;
        date) SORT='3';;
        size) SORT='5';;
        se) SORT='7';;
        le) SORT='9';;
        author) SORT='11';;
        category) SORT='13';;
    esac
    [ -n "$sort_reverse" ] && SORT="$(expr "$SORT" + '1')"
}

tpb_fields="category,size,date,name,seeders,leechers,author,link"

tpb_page() {
    t1="$(ucurl -s "$DOMAIN/search/$SEARCHP/$PAGE/$SORT/0" | reliq 'td' | sed 's/<i>Anonymous<\/i>/<a class="detDesc">Anonymous<\/a>/g')"
    out_tmp="$(echo "$t1" | grep -oE 'magnet:\?[^"]+')" #magnet
    out_lines="$(echo "$t1" | reliq '
        center; a | "%i\n" / sed "N;s/.*\n//",
        font .detDesc | "%i\n" / sed "s/.* Size ([0-9.]+)&nbsp;([^,]+),.*/\1 \2/p" "nE",
        font .detDesc | "%i\n" / sed "s/.*Uploaded //;s/&nbsp;/-/;s/,.*//" "E",
        a .detLink title | "%i\n",
        td align=right | "%i\n" / sed "N; s/\n.*//",
        td align=right | "%i\n" / sed "N; s/.*\n//",
        a .detDesc | "%i\n"
    ' | pastelines 7 "$C_CATEGORY,$C_SIZE,$C_DATE,$C_NAME,$C_SE,$C_LE,$C_AUTHOR")"
}

tpb_link_conv() {
    echo "$1"
}

tpb_out() {
    echo "$out_tmp" | sed "$1q;d"
}

lt_help() {
    printf '  -s,  --sort TYPE\t\tsort using TYPE that can be: name, size, date, se, le\n"'
}

lt_searchtrans() {
    tr ' .+/_:;' '-'
}

lt_settings() {
    [ -z "$DOMAIN" ] && DOMAIN="https://www.limetorrents.lol/"
    SORT=''
    case "$sort_type" in
        name) SORT='';;
        size) SORT='size';;
        date) SORT='time';;
        se) SORT='seeds';;
        le) SORT='leechs';;
    esac
}

lt_fields="name,date,size,seeders,leechers,health,link"

lt_page() {
    t1="$(ucurl -g -L -s "$DOMAIN/search/all/$SEARCHP/$SORT/$PAGE/" )"
    out_tmp="$(echo "$t1" | reliq 'td +class="tdleft"; a +href=e>".html" | "'$DOMAIN'%(href)v\n"')"
    out_lines="$(echo "$t1" | reliq '
        table class=table2; {
            td class=tdleft; a href=e>.html | "%i\n",
            td .tdnormal | "%i\n" / sed "/ - /!d; s/ - .*//",
            td .tdnormal | "%i\n" / sed "/ - /d",
            td .tdseed | "%i\n",
            td .tdleech | "%i\n",
            td .tdright; div | "%(class)v\n"
        }
    ' | pastelines 6 "$C_NAME,$C_DATE,$C_SIZE,$C_SE,$C_LE,$C_HEALTH")"
}

lt_link_conv() {
    ucurl -L -g -s "$1" | grep -oE -m 1 'magnet:\?[^"]+'
}

lt_out() {
    lt_link_conv "$(echo "$out_tmp" | sed "s/ /%20/g; $1q;d")"
}

t1337x_help() {
    printf '  -s,  --sort TYPE\t\tsort using TYPE that can be: name, size, date, se, le\n"'
    printf "  -r,  --reverse\t\tsort in reverse\n"
}

t1337x_searchtrans() {
    tr ' .+/_:;' '-'
}

t1337x_settings() {
    [ -z "$DOMAIN" ] && DOMAIN="https://www.1337xx.to"
    if [ -z "$sort_type" ]
    then
        SORT=''
        RSORT=""
        PSORT="search"
    else
        case "$sort_type" in
            name) SORT='';;
            size) SORT='size';;
            date) SORT='time';;
            se) SORT='seeders';;
            le) SORT='leechers';;
        esac
        PSORT="sort-search"
        [ -z "$sort_reverse" ] && RSORT="desc" || RSORT="asc"
    fi
}

t1337x_fields="name,date,size,seeders,leechers,author,link"

t1337x_page() {
    llink="$DOMAIN/$PSORT/$SEARCHP/$SORT/$RSORT/$PAGE/"
    if [ -z "$SORT" ]
    then
        llink="$DOMAIN/search/$SEARCHP/$PAGE/"
    fi
    t1="$(ucurl -s "$llink")"
    out_tmp="$(echo "$t1" | reliq 'tbody; a href=b>/torrent/ | "'$DOMAIN'%(href)v\n"')" #links
    out_lines="$(echo "$t1" | reliq '
        tbody; {
            a href=b>/torrent/ | "%i\n",
            td .coll-date | "%i\n",
            td .coll-4 | "%i\n" / sed "s/<.*//",
            td class="coll-2 seeds" | "%i\n",
            td class="coll-3 leeches" | "%i\n",
            td .coll-5; a | "%i\n"
        }
    ' | pastelines 6 "$C_NAME,$C_DATE,$C_SIZE,$C_SE,$C_LE,$C_AUTHOR")"
}

t1337x_link_conv() {
    ucurl -g -s "$1" | grep -oE -m 1 'magnet:\?[^"]+'
}

t1337x_out() {
    t1337x_link_conv "$(echo "$out_tmp" | sed "$1q;d")"
}

rarbg_help() {
    printf '  -c,  --categories CATEGORIES\tsearch one of the categories: movies, anime, xxx, tv, apps, games, doc, music, other\n'
    printf '  -s,  --sort TYPE\t\tsort using TYPE that can be: name, size, date, se, le\n'
    printf "  -r,  --reverse\t\tsort in reverse\n"
}

rarbg_searchtrans() {
    sed 's/+/%2B/g; s/;/%3B/g; s/\//%2F/g; s/?/%3F/g; s/\$/%24/g; s/@/%40/g; s/#/%23/g; s/%/%25/g; s/&/%26/g; s/ /+/g;'
}

rarbg_settings() {
    [ -z "$DOMAIN" ] && DOMAIN="https://www.rarbgo.to"
    RSORT="ASC"
    SORT=''
    case "$sort_type" in
        name) SORT='';;
        size) SORT='size';;
        date) SORT='data';;
        se) SORT='seeders';;
        le) SORT='leechers';;
    esac
    [ -z "$sort_reverse" ] && RSORT="DESC"
    [ -n "$SORT" ] && SORT="&order=$SORT&by=$RSORT"
    [ -n "$categories_type" ] && CATEGORIES="&category=$categories_type"
}

rarbg_fields="name,date,size,seeders,leechers,author,link"

rarbg_page() {
    t1="$(ucurl -s -L -g "$DOMAIN/search/$PAGE/?search=$SEARCHP$SORT$CATEGORIES")"
    out_tmp="$(echo "$t1" | reliq 'table .tablelist2; td; a title | "'"$DOMAIN"'%(href)v\n"')" #links
    out_lines="$(echo "$t1" | reliq '
        table .tablelist2; {
            td; a title | "%i\n",
            td .tlista width=150px c@[0] | "%i\n",
            td .tlista width=100px | "%i\n",
            font color | "%i\n",
            td .tlista width=50px c@[0] | "%i\n",
            td .tlista -width align=center | "%i\n"
        }
    ' | pastelines 6 "$C_NAME,$C_DATE,$C_SIZE,$C_SE,$C_LE,$C_AUTHOR")"
}

rarbg_link_conv() {
    ucurl -g -s "$1" | grep -oE -m 1 'magnet:\?[^"]+' #!! cloudflare
}

rarbg_out() {
    rarbg_link_conv "$(echo "$out_tmp" | sed "$1q;d")"
}

nyaa_help() {
    printf '  -s,  --sort TYPE\t\tsort using TYPE that can be: name, comments, size, date, se, le, downloads\n'
    printf "  -r,  --reverse\t\tsort in reverse\n"
    printf '  -f,  --filter\t\t\tset filter to: no, no-remakes, no-trusted\n'
    printf '  -c,  --categories\t\tsearch one of the categories:\n'
    printf '\t  all\n'
    printf '\t  anime, anime-music-video, anime-english-translated,\n\t  anime-non-english-translated, anime-raw\n'
    printf '\t  audio, audio-lossless, audio-lossy\n'
    printf '\t  literature, literature-english-translated,\n\t  literature-non-english-translated, literature-raw\n'
    printf '\t  live-action, live-action-english-translated, live-action-idol-promotional-video,\n\t  live-action-non-english-translated, live-action-raw\n'
    printf '\t  pictures, pictures-graphics, pictures-photos\n'
    printf '\t  software, software-applications, software-games\n'
}

nyaa_searchtrans() {
    tr ' ' '+'
}

nyaa_settings() {
    [ -z "$DOMAIN" ] && DOMAIN="https://nyaa.si"
    RSORT="asc"
    CATEGORIES='0_0'
    FILTER='0'

    SORT=''
    case "$sort_type" in
        name) SORT='';;
        comments) SORT='comments';;
        size) SORT='size';;
        date) SORT='id';;
        se) SORT='seeders';;
        le) SORT='leechers';;
        downloads) SORT='downloads';;
    esac

    [ -z "$sort_reverse" ] && RSORT="desc"
    if [ -n "$filter_type" ]
    then
        case "$filter_type" in
            no) FILTER='0';;
            no-remakes) FILTER='1';;
            trusted) FILTER='2';;
        esac
    fi
    if [ -n "$categories_type" ]
    then
        case "$categories_type" in
            all) CATEGORIES='0_0';;
            anime) CATEGORIES='1_0';;
            anime-music-video) CATEGORIES='1_1';;
            anime-english-translated) CATEGORIES='1_2';;
            anime-non-english-translated) CATEGORIES='1_3';;
            anime-raw) CATEGORIES='1_4';;
            audio) CATEGORIES='2_0';;
            audio-lossless) CATEGORIES='2_1';;
            audio-lossy) CATEGORIES='2_2';;
            literature) CATEGORIES='3_0';;
            literature-english-translated) CATEGORIES='3_1';;
            literature-non-english-translated) CATEGORIES='3_2';;
            literature-raw) CATEGORIES='3_3';;
            live-action) CATEGORIES='4_0';;
            live-action-english-translated) CATEGORIES='4_1';;
            live-action-idol-promotional-video) CATEGORIES='4_2';;
            live-action-non-english-translated) CATEGORIES='4_3';;
            live-action-raw) CATEGORIES='4_4';;
            pictures) CATEGORIES='5_0';;
            pictures-graphics) CATEGORIES='5_1';;
            pictures-photos) CATEGORIES='5_2';;
            software) CATEGORIES='6_0';;
            software-applications) CATEGORIES='6_1';;
            software-games) CATEGORIES='6_2';;
        esac
    fi
}

rarbg_fields="category,name,size,date,seeders,leechers,downloaded,link"

nyaa_page() {
    t1="$(ucurl -s "$DOMAIN/?f=$FILTER&c=$CATEGORIES&q=$SEARCHP&s=$SORT&o=$RSORT&p=$PAGE")"
    out_tmp="$(echo "$t1" | reliq 'table .torrent-list; td class; a href=b>magnet:? | "%(href)v\n"')"
    out_lines="$(echo "$t1" | reliq '
        table .torrent-list; {
            a href=B>/?c=[0-9]_[0-9]; img .category-icon alt | "%(alt)v\n",
            td colspan=2; a href=E>/view/[0-9]+ | "%i\n",
            td class m@e>"iB" | "%i\n",
            td class data-timestamp | "%i\n",
            td class m@E>"^[0-9]+$" | "%i\n" / sed "N;N; s/\n.*//",
            td class m@E>"^[0-9]+$" | "%i\n" / sed "N;N; s/.*\n(.*)\n.*/\1/" "E",
            td class m@E>"^[0-9]+$" | "%i\n" / sed "N;N; s/.*\n//"
        }
    ' | pastelines 7 "$C_CATEGORY,$C_NAME,$C_SIZE,$C_DATE,$C_SE,$C_LE,$C_DOWNLOADED")"
}

nyaa_link_conv() {
    echo "$1"
}

nyaa_out() {
    echo "$out_tmp" | sed "$1q;d"
}

libgen_help() {
    printf '  -s,  --sort TYPE\t\tsort using TYPE that can be: id, name, publisher, date, pages, lang, size, extension\n'
    printf "  -r,  --reverse\t\tsort in reverse\n"
    printf "  -S,  --searchby TYPE\t\tsearch by TYPE, that can be: def, name, author, series, publisher, date, isbn, lang, md5, tags, extension\n"
    printf "  -F,  --format FORMAT\t\tspecify file format for results\n"
    printf "  -l,  --language LANG\t\tspecify language for results (only for fiction)\n"
    printf "  -m,  --mode MODE\t\tsearches in chosen MODE which can be: nf|non-fiction, f|fiction, s|science\n"
    printf "  -M,  --mask\t\t\tuse wildcards for PATTERN\n"
    printf "  -R,  --results NUM\t\tshow NUM results\n"
}

libgen_searchtrans() {
    tr ' ' '+'
}

libgen_settings() {
    [ -z "$DOMAIN" ] && DOMAIN="https://libgen.st"

    [ -z "$RESULTS" ] && RESULTS='25'

    MODE='0'
    case "$mode_type" in
        nf|non-fiction) MODE='0';;
        f|fiction) MODE='1';;
        s|science) MODE='2';;
    esac

    SORT=''
    case "$sort_type" in
        id) SORT='id';;
        name) SORT='title';;
        publisher) SORT='publisher';;
        date) SORT='year';;
        pages) SORT='pages';;
        lang) SORT='language';;
        size) SORT='filesize';;
        extension) SORT='extension';;
    esac
    RSORT="DESC"
    [ -z "$sort_reverse" ] && RSORT="ASC"

    SEARCHBY='def'
    case "$searchby_type" in
        def) SEARCHBY="def";;
        name) SEARCHBY="title";;
        author) SEARCHBY="author";;
        series) SEARCHBY="series";;
        publisher) SEARCHBY="publisher";;
        date) SEARCHBY="year";;
        isbn) SEARCHBY="identifier";;
        lang) SEARCHBY="language";;
        md5) SEARCHBY="md5";;
        tags) SEARCHBY="tags";;
        extension) SEARCHBY="extension";;
    esac

    LANG="";

    MASK='1'
    [ -n "$mask_enable" ] && MASK='0'
}

libgen_0_fields="name,pages,size,date,author,extension,link"
libgen_1_fields="name,author,size,extension,language,link"
libgen_2_fields="name,author,size,volume,link"

libgen_page() {
    case $MODE in
        0)
            t1="$(ucurl -s "$DOMAIN/search.php?req=$SEARCHP&open=0&res=$RESULTS&view=detailed&phrase=$MASK&column=$SEARCHBY&page=$PAGE&sort=$SORT&sortmode=$RSORT" | tr -d '\r' | reliq 'table rules=cols width=100% border=0; tr l@[2]')"
            out_tmp="$(echo "$t1" | reliq 'td colspan=2' | grep -oE '\?md5=[A-Z0-9]+' | sed 's/^?md5=/http:\/\/library.lol\/main\//')" #!!
            out_lines="$(echo "$t1" | reliq '
                td colspan=2; a | "%i\n",
                td C@"font m@f>\"Pages:\""; [0] td ssub@ | "%i\n" / sed "s/<.*//",
                td C@"font m@f>\"Size:\""; [0] td ssub@ | "%i\n" / sed "s/ (.*//",
                td C@"font m@f>\"Year:\""; [0] td ssub@ | "%i\n",
                td colspan=3; b; { a | "%i," } | sed "s/, /,/g" echo "" "\n",
                td C@"font m@f>\"Extension:\""; [0] td ssub@ | "%i\n"
            ' | pastelines 6 "$C_NAME,$C_PAGES,$C_SIZE,$C_DATE,$C_AUTHOR,$C_EXTENSION")";;
        1)
            [ "$SEARCHBY" = 'def' ] && SEARCHBY=""
            [ "$MASK" -eq 1 ] && MASK=0 || MASK=1

            t1="$(ucurl -s "$DOMAIN/fiction/?q=$SEARCHP&criteria=$SEARCHBY&language=$LANG&wildcard=$MASK&format=$FORMAT&page=$PAGE")"
            out_tmp="$(echo "$t1" | reliq 'tbody; tr; ul +class="record_mirrors_compact" | "%i\n" / sed "s/^<li><a href=\"//; s/\".*//" "E"')"
            out_lines="$(echo "$t1" | reliq '
                tbody; tr; {
                    td; a -title | "%i\n",
                    ul +class="catalog_authors" | "%i\n" / sed "s/\t//g; /^$/d; s/^<li>//g; s/<li>/,/g; s/<\/li>//g; s/<a href=?(\"|'\'')[^\"'\'']+?(\"|'\'') title=?(\"|'\'')[^\"'\'']+?(\"|'\'')>//g; s/<\/a>//g; s/, /,/g" "E",
                    td title | "%i\n" / sed "s/.* //",
                    td title | "%i\n" / sed "s/ .*//" tr "A-Z" "a-z",
                    td -title c@[0] | "%i\n" / sed "N;s/.*\n//"
                }
            ' | pastelines 5 "$C_NAME,$C_AUTHOR,$C_SIZE,$C_EXTENSION,$C_LANGUAGE")";;
        2)
            t1="$(ucurl -s "$DOMAIN/scimag/?q=$SEARCHP&page=$PAGE")"
            out_tmp="$(echo "$t1" | reliq 'tbody; tr; td; ul; a href [0] | "%(href)v\n"')"
            out_lines="$(echo "$t1" | reliq '
                tbody; tr; td; {
                    p; a | "%i\n" / sed "N; s/\n/ - /",
                    td -style c@[0] | "%i\n",
                    td m@"title=\"edit metadata\"" | "%i\n" / sed "s/<.*//;s/&nbsp;//",
                    td; p m@b>"volume" | "%i\n" / sed "s/&nbsp;//g"
                }
            ' | pastelines 4 "$C_NAME,$C_AUTHOR,$C_SIZE,$C_VOLUME")";;
            #echo "$t1" | sed -E '/^[[:space:]]+<p>DOI: [^<>]+<\/p>/!d; s/.*DOI: //; s/<\/p>.*//' #doi
    esac
}

libgen_link_conv() {
    if echo "$1" | grep '://sci-hub' -q
    then
        ucurl -g -s "$1" | reliq 'embed | "%(src)v\n"' | sed 's/^/https:/'
    else
        ucurl -g -s "$1" | reliq 'h2; a href l@[1] | "%(href)v\n"'
    fi
}

libgen_out() {
    libgen_link_conv "$(echo "$out_tmp" | sed "s/ /%20/g; ${NUMBER}q;d")"
}

get_results() {
    results="$(for i in $(echo "$2" | sed 's/[,\/|]/ /g' | tr -cd '0-9 \n' | sort -u)
    do
        [ -z "i" ] && continue
        $1 "$i" | if [ -n "$NOCLIPBOARD" ]
        then
            head -n1
        else
            tee /dev/stderr | head -n1
        fi
    done)"
    if [ -n "$NOCLIPBOARD" ]
    then
        echo "$results"
    else
        echo "$results" | xclip -r -sel clip
    fi
}

link_conv_out() {
    for i in $1
    do
        ${basesite}_link_conv "$i"
    done
}

conv_to_csv() {
    [ "$LINK_CONV" -eq 1 ] && out_tmp="$(link_conv_out "$out_tmp")"
    echo "$out_lines" | awk -v "links_raw=$(echo "$out_tmp" | tr '\n' '\t')" '
        BEGIN {
            ORS = ""
            l=1;
            split(links_raw,links,"\t");
        }
        {
            print $0, "'"$DELIM"'", links[l++], "\n";
        }
    '
}

if [ "$#" -eq '0' ]
then
    print_help >&2
    exit 1
fi

case "$1" in
    tpb|thepiratebay) basesite="tpb";;
    lt|limetorrents) basesite="lt";;
    rarbg) basesite="rarbg";;
    nyaa) basesite="nyaa";;
    1337x) basesite="t1337x";;
    libgen) basesite="libgen";;
    *) print_help >&2; exit 1;
esac
shift

[ $# -eq 0 ] && { ${basesite}_help; exit 1; }

while [ $# -gt 0 ]
do
    case "$1" in
        -s|--sort)
            sort_type="$2"
            shift;;
        -h|--help)
            ${basesite}_help >&2;
            exit 1;;
        --no-csv-header)
            CSV_HEADER=0;;
        --csv)
            COLOR=0
            JSON=0
            CSV=1;;
        --json)
            COLOR=0
            CSV=0
            JSON=1;;
        --link-conv)
            LINK_CONV=1;;
        -r|--reverse)
            sort_reverse='1';;
        -R|--results)
            RESULTS="$1"
            shift;;
        -f|--filter)
            filter_type="$2"
            shift;;
        -c|--categories)
            categories_type="$2"
            shift;;
        -S|--searchby)
            searchby_type="$2"
            shift;;
        -m|--mode)
            mode_type="$2"
            shift;;
        -M|--mask)
            mask_enable="$2";;
        -C|--no-color)
            COLOR=0;;
        -p|--page)
            PAGE="$2"
            shift;;
        -d|--domain)
            DOMAIN="$2"
            shift;;
        -F|--format)
            FORMAT="$2"
            shift;;
        -l|--language)
            LANG="$2"
            shift;;
        -D|--delimiter)
            DELIM="$2"
            shift;;
        --no-prompt)
            NOPROMPT='1';;
        --no-clipboard)
            NOCLIPBOARD='1';;
        --choose)
            COMMAND="$2"
            shift;;
        *)
            if [ -z "$SEARCH" ]
            then
              SEARCH="$1"
            else
              SEARCH="$SEARCH $1"
            fi;;
    esac
    shift
done

SEARCHP="$(echo "$SEARCH" | ${basesite}_searchtrans)"

${basesite}_settings
${basesite}_page

[ -z "$out_tmp" ] && exit 1


if [ "$CSV" -eq 1 ]
then
    [ "$CSV_HEADER" -eq 1 ] && eval 'echo "$'"${basesite}_fields"'" | tr , "'"$DELIM"'"'
    conv_to_csv
    exit
fi

out_lines="$(echo "$out_lines" | nl)"

if [ -n "$COMMAND" ]
then
    NUMBERS="$(echo "$out_lines" | eval "$COMMAND")"
else
    echo "$out_lines"
    [ -z "$NOPROMPT" ] && printf 'num> '
    read -r NUMBERS
fi

get_results "${basesite}_out" "$NUMBERS"
